config/routes.rb
Memoristas::Application.routes.draw do
  resources :personas

  resources :carreras

  

end

app/models/carrera.rb
class Carrera < ActiveRecord::Base
end

app/models/persona.rb
class Persona < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carreras_controller.rb
class CarrerasController < ApplicationController
  before_action :set_carrera, only: [:show, :edit, :update, :destroy]

  # GET /carreras
  # GET /carreras.json
  def index
    @carreras = Carrera.all
  end

  # GET /carreras/1
  # GET /carreras/1.json
  def show
  end

  # GET /carreras/new
  def new
    @carrera = Carrera.new
  end

  # GET /carreras/1/edit
  def edit
  end

  # POST /carreras
  # POST /carreras.json
  def create
    @carrera = Carrera.new(carrera_params)

    respond_to do |format|
      if @carrera.save
        format.html { redirect_to @carrera, notice: 'Carrera was successfully created.' }
        format.json { render action: 'show', status: :created, location: @carrera }
      else
        format.html { render action: 'new' }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carreras/1
  # PATCH/PUT /carreras/1.json
  def update
    respond_to do |format|
      if @carrera.update(carrera_params)
        format.html { redirect_to @carrera, notice: 'Carrera was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @carrera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carreras/1
  # DELETE /carreras/1.json
  def destroy
    @carrera.destroy
    respond_to do |format|
      format.html { redirect_to carreras_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrera
      @carrera = Carrera.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrera_params
      params.require(:carrera).permit(:nombre_carrera, :coordinador_carrera)
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render action: 'show', status: :created, location: @persona }
      else
        format.html { render action: 'new' }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:run_persona, :nombre_persona, :apellido_persona, :email_persona, :fono_persona)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carreras_helper.rb
module CarrerasHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/carreras/_form.html.erb
<%= form_for(@carrera) do |f| %>
  <% if @carrera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carrera.errors.count, "error") %> prohibited this carrera from being saved:</h2>

      <ul>
      <% @carrera.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre_carrera %><br>
    <%= f.text_field :nombre_carrera %>
  </div>
  <div class="field">
    <%= f.label :coordinador_carrera %><br>
    <%= f.text_field :coordinador_carrera %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carreras/edit.html.erb
<h1>Editing carrera</h1>

<%= render 'form' %>

<%= link_to 'Show', @carrera %> |
<%= link_to 'Back', carreras_path %>

app/views/carreras/index.html.erb
<h1>Listing carreras</h1>

<table>
  <thead>
    <tr>
      <th>Nombre carrera</th>
      <th>Coordinador carrera</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carreras.each do |carrera| %>
      <tr>
        <td><%= carrera.nombre_carrera %></td>
        <td><%= carrera.coordinador_carrera %></td>
        <td><%= link_to 'Show', carrera %></td>
        <td><%= link_to 'Edit', edit_carrera_path(carrera) %></td>
        <td><%= link_to 'Destroy', carrera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carrera', new_carrera_path %>

app/views/carreras/new.html.erb
<h1>New carrera</h1>

<%= render 'form' %>

<%= link_to 'Back', carreras_path %>

app/views/carreras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre carrera:</strong>
  <%= @carrera.nombre_carrera %>
</p>

<p>
  <strong>Coordinador carrera:</strong>
  <%= @carrera.coordinador_carrera %>
</p>

<%= link_to 'Edit', edit_carrera_path(@carrera) %> |
<%= link_to 'Back', carreras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memoristas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :run_persona %><br>
    <%= f.text_field :run_persona %>
  </div>
  <div class="field">
    <%= f.label :nombre_persona %><br>
    <%= f.text_field :nombre_persona %>
  </div>
  <div class="field">
    <%= f.label :apellido_persona %><br>
    <%= f.text_field :apellido_persona %>
  </div>
  <div class="field">
    <%= f.label :email_persona %><br>
    <%= f.text_field :email_persona %>
  </div>
  <div class="field">
    <%= f.label :fono_persona %><br>
    <%= f.text_field :fono_persona %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1>Listing personas</h1>

<table>
  <thead>
    <tr>
      <th>Run persona</th>
      <th>Nombre persona</th>
      <th>Apellido persona</th>
      <th>Email persona</th>
      <th>Fono persona</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.run_persona %></td>
        <td><%= persona.nombre_persona %></td>
        <td><%= persona.apellido_persona %></td>
        <td><%= persona.email_persona %></td>
        <td><%= persona.fono_persona %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>New persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Run persona:</strong>
  <%= @persona.run_persona %>
</p>

<p>
  <strong>Nombre persona:</strong>
  <%= @persona.nombre_persona %>
</p>

<p>
  <strong>Apellido persona:</strong>
  <%= @persona.apellido_persona %>
</p>

<p>
  <strong>Email persona:</strong>
  <%= @persona.email_persona %>
</p>

<p>
  <strong>Fono persona:</strong>
  <%= @persona.fono_persona %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>